<template>
  <div class="container">
    <h1 class="page-title">Pokédex</h1>

    <div class="search-container">
      <div class="search-wrapper">
        <input
          v-model="searchQuery"
          type="text"
          placeholder="Search Pokémon..."
          class="search-input"
        />
        <button
          v-if="searchQuery"
          @click="searchQuery = ''"
          class="clear-button"
          aria-label="Clear search"
        >
          ✕
        </button>
      </div>
    </div>

    <div class="flex justify-center mb-6">
      <NuxtLink
        to="/compare"
        class="px-4 py-2 bg-purple-500 text-white rounded-lg hover:bg-purple-600 transition-colors"
      >
        Compare Pokémon
      </NuxtLink>
    </div>

    <div v-if="pokemon.length" class="pokemon-grid">
      <PokemonCard
        v-for="pokemon in filteredPokemon"
        :key="pokemon.id"
        :pokemon="pokemon"
      />
    </div>
    <div v-else class="text-center text-gray-600">Loading Pokémon...</div>
  </div>
</template>

<script setup>
const pokemon = ref([]);
const searchQuery = ref("");

const filteredPokemon = computed(() => {
  // Convert the search query to lowercase for case-insensitive comparison
  const query = searchQuery.value.toLowerCase();

  // Filter the list of Pokémon
  return pokemon.value.filter((pokemonItem) => {
    // Check if the Pokémon item and its name exist
    if (!pokemonItem || !pokemonItem.name) {
      return false;
    }

    // Convert the Pokémon's name to lowercase
    const nameInLowerCase = pokemonItem.name.toLowerCase();

    // Return true if the name includes the search query, false otherwise
    return nameInLowerCase.includes(query);
  });
});

// Beginner friendly version
// onMounted(async () => {
//   try {
//     const results = [];
//     // Fetch 150 Pokémons from the API
//     // Using Array.from to create an array of promises
//     // Each promise fetches a Pokémon by its ID
//     // The ID is generated by adding 1 to the index (i) of the array
//     // This way, we fetch Pokémon from 1 to 151
//     // The API returns a JSON response for each Pokémon
//     // The responses are stored in the 'responses' array
//     // Finally, we filter out any null responses
//     // and assign the valid Pokémon data to the 'pokemon' variable
//     for (let i = 1; i <= 151; i++) {
//       const { data, error } = await useFetch(
//         `https://pokeapi.co/api/v2/pokemon/${i}`
//       );
//       if (error.value) {
//         console.error(`Error fetching Pokemon ${i}:`, error.value);
//       } else {
//         results.push(data.value);
//       }
//     }
//     // Assign the successfully fetched Pokemon to the reactive variable
//     pokemon.value = results;
//   } catch (error) {
//     console.error("Error fetching Pokemon:", error);
//     pokemon.value = [];
//   }
// });

//Fetches all Pokémon at once -> Faster but less beginner friendly
onMounted(async () => {
  try {
    const responses = await Promise.all(
      Array.from({ length: 151 }, (_, i) =>
        fetch(`https://pokeapi.co/api/v2/pokemon/${i + 1}`)
          .then((res) => res.json())
          .catch((error) => {
            console.error(`Error fetching Pokemon ${i + 1}:`, error);
            return null;
          })
      )
    );
    pokemon.value = responses.filter((p) => p !== null);
  } catch (error) {
    console.error("Error fetching Pokemon:", error);
    pokemon.value = [];
  }
});
</script>
